[[mapping]]
single_output = "index"
template = "index.html"
selector = '.[] | select(.tag=="projects_index")'

[[mapping]]
per_match_output = "jq:.title"
template = "item.html"
selector = '.[] | select(.tag=="testitem")'
